---

- hosts: all
  tasks:
  - name: Update all packages
    become: true
    become_method: "{{ 'su' if ansible_distribution == 'Debian' else 'sudo' }}"
    package:
      name: "*"
      state: latest
      update_cache: yes
