---

- hosts: ubuntu
  become: yes
  tasks:

  - name: Update all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes

- hosts: redhat
  become: yes
  tasks:

  - name: Update all packages
    dnf:
      name: "*"
      state: latest
